cloud:
  aws:
    region:
      static: us-east-1
    stack:
      auto: false
    credentials:
      profile-name: dev
logging:
  level:
    com:
      amazonaws:
        request: debug
        internal:
          InstanceMetadataServiceResourceFetcher: error
        util:
          EC2MetadataUtils: error